import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AdminApiService } from '../../../admin-api.service';
import { WorkspaceMetadata, CreateWorkspaceRequest, UpdateWorkspaceRequest } from '../workspace-metadata.interface';

interface LanguageOption {
  code: string;
  name: string;
}

@Component({
  selector: 'app-workspace-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './workspace-form.component.html',
  styleUrls: ['./workspace-form.component.less']
})
export class WorkspaceFormComponent implements OnInit {
  isEditMode = signal(false);
  workspaceId = signal<string | null>(null);
  adminKey = signal<string | null>(null);

  // Form data
  formData = signal<WorkspaceMetadata>({
    date: '',
    city: '',
    country: '',
    venue: '',
    event_name: '',
    interactive_workshop: false,
    languages: [],
    facilitator_names: [''],
    keywords: [],
    'context-label': '',
    source: '',
    'email-template': ''
  });

  publicVisible = signal(false);
  collaborate = signal(false);

  // Available options
  availableLanguages: LanguageOption[] = [
    { code: 'he', name: 'Hebrew' },
    { code: 'ar', name: 'Arabic' },
    { code: 'en', name: 'English' },
    { code: 'nl', name: 'Dutch' }
  ];

  availableKeywords: string[] = [
    'Migration', 'Identity', 'Community', 'History', 'Culture',
    'Memory', 'Family', 'Work', 'Education', 'Art'
  ];

  // Temporary input for adding keywords
  newKeyword = signal('');

  // UI state
  isSubmitting = signal(false);
  errorMessage = signal<string | null>(null);

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private adminApi: AdminApiService
  ) {}

  ngOnInit() {
    // Check if we're in edit mode
    this.route.params.subscribe(params => {
      if (params['workspaceId']) {
        this.isEditMode.set(true);
        this.workspaceId.set(params['workspaceId']);
      }
    });

    // Get admin key from query params (for edit mode)
    this.route.queryParams.subscribe(params => {
      if (params['key']) {
        this.adminKey.set(params['key']);
      }
    });

    // Load workspace data if in edit mode
    if (this.isEditMode() && this.workspaceId() && this.adminKey()) {
      this.loadWorkspaceData();
    }
  }

  loadWorkspaceData() {
    const id = this.workspaceId();
    const key = this.adminKey();
    if (!id || !key) return;

    this.adminApi.getWorkspace(id, key).subscribe({
      next: (workspace) => {
        if (workspace.metadata) {
          this.formData.set({ ...workspace.metadata });
          // Ensure facilitator_names is an array
          if (!this.formData().facilitator_names || this.formData().facilitator_names.length === 0) {
            this.formData.update(data => ({ ...data, facilitator_names: [''] }));
          }
        }
      },
      error: (error) => {
        console.error('Error loading workspace:', error);
        this.errorMessage.set('Failed to load workspace data. Please check the admin key.');
      }
    });
  }

  isLanguageSelected(code: string): boolean {
    return this.formData().languages.includes(code);
  }

  toggleLanguage(code: string) {
    const currentLanguages = [...this.formData().languages];
    const index = currentLanguages.indexOf(code);

    if (index > -1) {
      currentLanguages.splice(index, 1);
    } else {
      currentLanguages.push(code);
    }

    this.formData.update(data => ({ ...data, languages: currentLanguages }));
    this.updateAutoGeneratedFields();
  }

  isKeywordSelected(keyword: string): boolean {
    return this.formData().keywords?.includes(keyword) || false;
  }

  toggleKeyword(keyword: string) {
    const currentKeywords = [...(this.formData().keywords || [])];
    const index = currentKeywords.indexOf(keyword);

    if (index > -1) {
      currentKeywords.splice(index, 1);
    } else {
      currentKeywords.push(keyword);
    }

    this.formData.update(data => ({ ...data, keywords: currentKeywords }));
  }

  addFacilitatorName() {
    const names = [...this.formData().facilitator_names, ''];
    this.formData.update(data => ({ ...data, facilitator_names: names }));
  }

  removeFacilitatorName(index: number) {
    const names = [...this.formData().facilitator_names];
    if (names.length > 1) {
      names.splice(index, 1);
      this.formData.update(data => ({ ...data, facilitator_names: names }));
    }
  }

  updateFacilitatorName(index: number, value: string) {
    const names = [...this.formData().facilitator_names];
    names[index] = value;
    this.formData.update(data => ({ ...data, facilitator_names: names }));
  }

  updateAutoGeneratedFields() {
    const data = this.formData();

    // Generate context-label: '{City}, {Month Name} {Year}'
    if (data.date && data.city) {
      const dateObj = new Date(data.date);
      const monthName = dateObj.toLocaleDateString('en-US', { month: 'long' });
      const year = dateObj.getFullYear();
      data['context-label'] = `${data.city}, ${monthName} ${year}`;
    }

    // Generate source: '{YYYY}.{MM}.{DD} - {Venue}/{Event Name}'
    if (data.date && data.venue && data.event_name) {
      const [year, month, day] = data.date.split('-');
      data.source = `${year}.${month}.${day} - ${data.venue}/${data.event_name}`;
    }

    // Generate email-template
    if (data.languages.length > 0) {
      const primaryLocale = data.languages[0];
      data['email-template'] = data.interactive_workshop
        ? `to-evaluate-${primaryLocale}`
        : `after-evaluate-${primaryLocale}`;
    }

    this.formData.set({ ...data });
  }

  onFieldChange() {
    this.updateAutoGeneratedFields();
  }

  isFormValid(): boolean {
    const data = this.formData();
    return !!(
      data.date &&
      data.city &&
      data.country &&
      data.venue &&
      data.event_name &&
      data.languages.length > 0 &&
      data.facilitator_names.length > 0 &&
      data.facilitator_names.every(name => name.trim().length > 0)
    );
  }

  onSubmit() {
    if (!this.isFormValid()) {
      this.errorMessage.set('Please fill in all required fields.');
      return;
    }

    this.isSubmitting.set(true);
    this.errorMessage.set(null);

    // Update auto-generated fields one last time
    this.updateAutoGeneratedFields();

    if (this.isEditMode()) {
      this.updateWorkspace();
    } else {
      this.createWorkspace();
    }
  }

  createWorkspace() {
    const request: CreateWorkspaceRequest = {
      metadata: this.formData(),
      public: this.publicVisible(),
      collaborate: this.collaborate()
    };

    this.adminApi.createWorkspace(request).subscribe({
      next: (workspace) => {
        console.log('Workspace created successfully:', workspace);
        this.router.navigate(['/admin'], {
          state: { message: 'Workspace created successfully!' }
        });
      },
      error: (error) => {
        console.error('Error creating workspace:', error);
        this.errorMessage.set(error.error?.message || 'Failed to create workspace. Please try again.');
        this.isSubmitting.set(false);
      }
    });
  }

  updateWorkspace() {
    const id = this.workspaceId();
    const key = this.adminKey();

    if (!id || !key) {
      this.errorMessage.set('Missing workspace ID or admin key.');
      this.isSubmitting.set(false);
      return;
    }

    const request: UpdateWorkspaceRequest = {
      metadata: this.formData()
    };

    this.adminApi.updateWorkspace(id, key, request, this.publicVisible(), this.collaborate()).subscribe({
      next: (response) => {
        console.log('Workspace updated successfully:', response);
        this.router.navigate(['/admin'], {
          state: { message: 'Workspace updated successfully!' }
        });
      },
      error: (error) => {
        console.error('Error updating workspace:', error);
        this.errorMessage.set(error.error?.message || 'Failed to update workspace. Please try again.');
        this.isSubmitting.set(false);
      }
    });
  }

  cancel() {
    this.router.navigate(['/admin']);
  }

  getLanguageName(code: string): string {
    return this.availableLanguages.find(l => l.code === code)?.name || code;
  }
}
